// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  content_index: dynamic(() => import("./ContentIndex")),
  education: dynamic(() => import("./Education")),
  extra_tech_list: dynamic(() => import("./ExtraTechList")),
  home_template: dynamic(() => import("./HomeTemplate")),
  tech_list: dynamic(() => import("./TechList")),
  text_block: dynamic(() => import("./TextBlock")),
  work_experience: dynamic(() => import("./WorkExperience")),
};
